# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d08b3131f3dbc143e87b34c7e5399976051c3117f17bf60babc124366d1afa59704cf22a0e144c50575bd8fefac2cad5ab1379849d83b9ce2bcc802370d7ca8

test:
  secret_key_base: d6a2df8086be2d2b9d43e41e63d472e85b94f8b58462a182faf4fa7103d7b7b5a43c27dd02433d51c9c593b9462a70711d369471370c662c4556a29b670abd92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
